### ISSUE TITLE
Restructure the policies and tokens definitions

### ISSUE THREAD

**Issue by khmarochos** [khmarochos/vault-cluster#1]
Instead of the following form:
```yaml
vault_policies:
  - name: policy_alpha
    parameter_foo: 1
    parameter_bar: 2
    parameter_baz: 3
vault_tokens:
  - name: token_alpha
    parameter_foo: 1
    parameter_bar: 2
    parameter_baz: 3
```
use the following one:
```yaml
vault_policies:
  policy_alpha:
    parameter_foo: 1
    parameter_bar: 2
    parameter_baz: 3
vault_tokens:
  token_alpha:
    parameter_foo: 1
    parameter_bar: 2
    parameter_baz: 3
```
